services:
  postgres:
    image: postgres:16
    container_name: note-postgres
    environment:
      POSTGRES_DB: note_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdkawsardev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
